export const MODAL_TYPES = {
  OFF: 0,
  LOGIN: 1,
  SIGNUP: 2,
  FORGOT: 3,
  VERIFY: 4,
  CONFIRM: 5,
  HUBSPOT: 6,
  NEW_SUBSCRIPTON: 7,
  UPLOAD_ABI: 8,
  NEW_DASHBOARD_FLOW: 9,
  MOBILE_INPUT_FIELD: 10,
};

export const DRAWER_TYPES = {
  OFF: 0,
  NEW_DASHBOARD: 1,
  NEW_DASHBOARD_ITEM: 2,
};

export const ALERT_TYPES = {
  OFF: 0,
  CLOSE_DRAWER: 1,
};
