"""Add score index

Revision ID: 784c8ec69ca7
Revises: a9060d0527e3
Create Date: 2024-06-12 18:34:40.978811

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "784c8ec69ca7"
down_revision = "a9060d0527e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_leaderboard_scores_leaderboard_id_version_score",
        "leaderboard_scores",
        ["leaderboard_id", "leaderboard_version_number", "score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_leaderboard_scores_leaderboard_id_version_score",
        table_name="leaderboard_scores",
    )
    # ### end Alembic commands ###
