"""Add score index

Revision ID: f2df6f288fe7
Revises: a9060d0527e3
Create Date: 2024-06-12 16:05:12.778202

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2df6f288fe7"
down_revision = "a9060d0527e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###\
    op.create_index(
        op.f("ix_leaderboard_scores_score"),
        "leaderboard_scores",
        ["score"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leaderboard_scores_score"), table_name="leaderboard_scores")
    # ### end Alembic commands ###
