name: Lint Moonstream crawlers

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "crawlers/**"
      - "!crawlers/deploy/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools
      - name: Install test requirements
        working-directory: ./crawlers/mooncrawl
        run: pip install -e .[dev]
      - name: Mypy type check
        working-directory: ./crawlers/mooncrawl
        run: mypy mooncrawl/
      - name: Black syntax check
        working-directory: ./crawlers/mooncrawl
        run: black --check mooncrawl/
